# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'areal_weight_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Areal_Weight(object):
    def setupUi(self, Areal_Weight):
        Areal_Weight.setObjectName("Areal_Weight")
        Areal_Weight.resize(555, 420)
        self.label = QtWidgets.QLabel(Areal_Weight)
        self.label.setGeometry(QtCore.QRect(20, 10, 491, 20))
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Areal_Weight)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 491, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMouseTracking(False)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.aw_source_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.aw_source_lineedit.setObjectName("aw_source_lineedit")
        self.horizontalLayout.addWidget(self.aw_source_lineedit)
        self.aw_source_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.aw_source_browse.setObjectName("aw_source_browse")
        self.horizontalLayout.addWidget(self.aw_source_browse)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Areal_Weight)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 80, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.aw_target_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.aw_target_lineedit.setObjectName("aw_target_lineedit")
        self.horizontalLayout_2.addWidget(self.aw_target_lineedit)
        self.aw_target_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.aw_target_browse.setObjectName("aw_target_browse")
        self.horizontalLayout_2.addWidget(self.aw_target_browse)
        self.frame = QtWidgets.QFrame(Areal_Weight)
        self.frame.setGeometry(QtCore.QRect(10, 30, 511, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 170, 491, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.aw_save_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.aw_save_lineedit.setObjectName("aw_save_lineedit")
        self.horizontalLayout_6.addWidget(self.aw_save_lineedit)
        self.aw_save_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.aw_save_browse.setObjectName("aw_save_browse")
        self.horizontalLayout_6.addWidget(self.aw_save_browse)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 130, 491, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.aw_output_suffix = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.aw_output_suffix.setObjectName("aw_output_suffix")
        self.horizontalLayout_8.addWidget(self.aw_output_suffix)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 90, 491, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.aw_intp_fields = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.aw_intp_fields.setObjectName("aw_intp_fields")
        self.horizontalLayout_9.addWidget(self.aw_intp_fields)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Areal_Weight)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 250, 511, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.aw_progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.aw_progressBar.setProperty("value", 0)
        self.aw_progressBar.setObjectName("aw_progressBar")
        self.horizontalLayout_7.addWidget(self.aw_progressBar)
        self.aw_run_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.aw_run_prog.setObjectName("aw_run_prog")
        self.horizontalLayout_7.addWidget(self.aw_run_prog)
        self.aw_cancel_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.aw_cancel_prog.setObjectName("aw_cancel_prog")
        self.horizontalLayout_7.addWidget(self.aw_cancel_prog)
        self.frame.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_6.raise_()

        self.retranslateUi(Areal_Weight)
        QtCore.QMetaObject.connectSlotsByName(Areal_Weight)
        Areal_Weight.setTabOrder(self.aw_source_lineedit, self.aw_source_browse)
        Areal_Weight.setTabOrder(self.aw_source_browse, self.aw_target_lineedit)
        Areal_Weight.setTabOrder(self.aw_target_lineedit, self.aw_target_browse)
        Areal_Weight.setTabOrder(self.aw_target_browse, self.aw_intp_fields)
        Areal_Weight.setTabOrder(self.aw_intp_fields, self.aw_output_suffix)
        Areal_Weight.setTabOrder(self.aw_output_suffix, self.aw_save_lineedit)
        Areal_Weight.setTabOrder(self.aw_save_lineedit, self.aw_save_browse)
        Areal_Weight.setTabOrder(self.aw_save_browse, self.aw_run_prog)
        Areal_Weight.setTabOrder(self.aw_run_prog, self.aw_cancel_prog)

    def retranslateUi(self, Areal_Weight):
        _translate = QtCore.QCoreApplication.translate
        Areal_Weight.setWindowTitle(_translate("Areal_Weight", "Form"))
        self.label.setText(_translate("Areal_Weight", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Areal Weighting Method</span></p></body></html>"))
        self.label_2.setText(_translate("Areal_Weight", "Source Shapefile:"))
        self.aw_source_lineedit.setPlaceholderText(_translate("Areal_Weight", "filepath and name of the source shapefile"))
        self.aw_source_browse.setText(_translate("Areal_Weight", "Browse"))
        self.label_3.setText(_translate("Areal_Weight", "Target Shapefile:"))
        self.aw_target_lineedit.setPlaceholderText(_translate("Areal_Weight", "filepath and name of the target shapefile"))
        self.aw_target_browse.setText(_translate("Areal_Weight", "Browse"))
        self.label_7.setText(_translate("Areal_Weight", "Save as:"))
        self.aw_save_lineedit.setPlaceholderText(_translate("Areal_Weight", "filepath and name of output shapefile"))
        self.aw_save_browse.setText(_translate("Areal_Weight", "Browse"))
        self.label_8.setText(_translate("Areal_Weight", "Output Field Suffix:"))
        self.aw_output_suffix.setPlaceholderText(_translate("Areal_Weight", "ex: _intp (population would become population_intp)"))
        self.label_9.setText(_translate("Areal_Weight", "Interpolation Field(s):"))
        self.aw_intp_fields.setPlaceholderText(_translate("Areal_Weight", "Name(s) of field(s) to interpolated, space separated"))
        self.aw_run_prog.setText(_translate("Areal_Weight", "Run"))
        self.aw_cancel_prog.setText(_translate("Areal_Weight", "Cancel"))

