# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expert_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Expert_Method(object):
    def setupUi(self, Expert_Method):
        Expert_Method.setObjectName("Expert_Method")
        Expert_Method.resize(628, 519)
        self.label = QtWidgets.QLabel(Expert_Method)
        self.label.setGeometry(QtCore.QRect(20, 10, 491, 20))
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Expert_Method)
        self.frame.setGeometry(QtCore.QRect(10, 30, 511, 381))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 330, 491, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.expert_save_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.expert_save_lineedit.setObjectName("expert_save_lineedit")
        self.horizontalLayout_6.addWidget(self.expert_save_lineedit)
        self.expert_save_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.expert_save_browse.setObjectName("expert_save_browse")
        self.horizontalLayout_6.addWidget(self.expert_save_browse)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 250, 491, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.expert_ra = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.expert_ra.setObjectName("expert_ra")
        self.horizontalLayout_8.addWidget(self.expert_ra)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 210, 491, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.expert_ba = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.expert_ba.setObjectName("expert_ba")
        self.horizontalLayout_9.addWidget(self.expert_ba)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 290, 491, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.expert_intp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.expert_intp.setObjectName("expert_intp")
        self.horizontalLayout_10.addWidget(self.expert_intp)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 491, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.expert_ru = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.expert_ru.setObjectName("expert_ru")
        self.horizontalLayout_5.addWidget(self.expert_ru)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 491, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.expert_tu = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.expert_tu.setText("")
        self.expert_tu.setObjectName("expert_tu")
        self.horizontalLayout_3.addWidget(self.expert_tu)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.expert_parcel_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.expert_parcel_lineedit.setObjectName("expert_parcel_lineedit")
        self.horizontalLayout_2.addWidget(self.expert_parcel_lineedit)
        self.expert_parcel_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.expert_parcel_browse.setObjectName("expert_parcel_browse")
        self.horizontalLayout_2.addWidget(self.expert_parcel_browse)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 50, 491, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.expert_nest_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.expert_nest_lineedit.setObjectName("expert_nest_lineedit")
        self.horizontalLayout_4.addWidget(self.expert_nest_lineedit)
        self.expert_nest_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.expert_nest_browse.setObjectName("expert_nest_browse")
        self.horizontalLayout_4.addWidget(self.expert_nest_browse)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMouseTracking(False)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.expert_source_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.expert_source_lineedit.setObjectName("expert_source_lineedit")
        self.horizontalLayout.addWidget(self.expert_source_lineedit)
        self.expert_source_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.expert_source_browse.setObjectName("expert_source_browse")
        self.horizontalLayout.addWidget(self.expert_source_browse)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Expert_Method)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 410, 511, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.expert_progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.expert_progressBar.setProperty("value", 0)
        self.expert_progressBar.setObjectName("expert_progressBar")
        self.horizontalLayout_7.addWidget(self.expert_progressBar)
        self.expert_run_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.expert_run_prog.setObjectName("expert_run_prog")
        self.horizontalLayout_7.addWidget(self.expert_run_prog)
        self.expert_cancel_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.expert_cancel_prog.setObjectName("expert_cancel_prog")
        self.horizontalLayout_7.addWidget(self.expert_cancel_prog)
        self.frame.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget_6.raise_()

        self.retranslateUi(Expert_Method)
        QtCore.QMetaObject.connectSlotsByName(Expert_Method)
        Expert_Method.setTabOrder(self.expert_source_lineedit, self.expert_source_browse)
        Expert_Method.setTabOrder(self.expert_source_browse, self.expert_nest_lineedit)
        Expert_Method.setTabOrder(self.expert_nest_lineedit, self.expert_nest_browse)
        Expert_Method.setTabOrder(self.expert_nest_browse, self.expert_parcel_lineedit)
        Expert_Method.setTabOrder(self.expert_parcel_lineedit, self.expert_parcel_browse)
        Expert_Method.setTabOrder(self.expert_parcel_browse, self.expert_tu)
        Expert_Method.setTabOrder(self.expert_tu, self.expert_ru)
        Expert_Method.setTabOrder(self.expert_ru, self.expert_ba)
        Expert_Method.setTabOrder(self.expert_ba, self.expert_ra)
        Expert_Method.setTabOrder(self.expert_ra, self.expert_intp)
        Expert_Method.setTabOrder(self.expert_intp, self.expert_save_lineedit)
        Expert_Method.setTabOrder(self.expert_save_lineedit, self.expert_save_browse)
        Expert_Method.setTabOrder(self.expert_save_browse, self.expert_run_prog)
        Expert_Method.setTabOrder(self.expert_run_prog, self.expert_cancel_prog)

    def retranslateUi(self, Expert_Method):
        _translate = QtCore.QCoreApplication.translate
        Expert_Method.setWindowTitle(_translate("Expert_Method", "Form"))
        self.label.setText(_translate("Expert_Method", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Expert System</span></p></body></html>"))
        self.label_7.setText(_translate("Expert_Method", "Save as:"))
        self.expert_save_lineedit.setPlaceholderText(_translate("Expert_Method", "filepath and name of output shapefile"))
        self.expert_save_browse.setText(_translate("Expert_Method", "Browse"))
        self.label_8.setText(_translate("Expert_Method", "Residential Area Field"))
        self.expert_ra.setPlaceholderText(_translate("Expert_Method", "Name of the field containing the residential area per parcel"))
        self.label_9.setText(_translate("Expert_Method", "Building Area Field"))
        self.expert_ba.setPlaceholderText(_translate("Expert_Method", "Name of the field containing the building area per parcel"))
        self.label_10.setText(_translate("Expert_Method", "Interpolation Field"))
        self.expert_intp.setPlaceholderText(_translate("Expert_Method", "Name of the field to interpolate, just one"))
        self.label_6.setText(_translate("Expert_Method", "Residential Units Field"))
        self.expert_ru.setPlaceholderText(_translate("Expert_Method", "Name of the field containing the number of residential units per parcel"))
        self.label_4.setText(_translate("Expert_Method", "Total Units Field:"))
        self.expert_tu.setPlaceholderText(_translate("Expert_Method", "Name of the field containing the total number of units per parcel"))
        self.label_3.setText(_translate("Expert_Method", "Parcel Shapefile:"))
        self.expert_parcel_lineedit.setPlaceholderText(_translate("Expert_Method", "filepath and name of the parcel shapefile"))
        self.expert_parcel_browse.setText(_translate("Expert_Method", "Browse"))
        self.label_5.setText(_translate("Expert_Method", "Nested Shapefile:"))
        self.expert_nest_lineedit.setPlaceholderText(_translate("Expert_Method", "filepath of nested shapefile. Ex: Tracts and tract groups"))
        self.expert_nest_browse.setText(_translate("Expert_Method", "Browse"))
        self.label_2.setText(_translate("Expert_Method", "Source Shapefile:"))
        self.expert_source_lineedit.setPlaceholderText(_translate("Expert_Method", "filepath and name of the source shapefile"))
        self.expert_source_browse.setText(_translate("Expert_Method", "Browse"))
        self.expert_run_prog.setText(_translate("Expert_Method", "Run"))
        self.expert_cancel_prog.setText(_translate("Expert_Method", "Cancel"))

