# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lv_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Limiting_Variable_Method(object):
    def setupUi(self, Limiting_Variable_Method):
        Limiting_Variable_Method.setObjectName("Limiting_Variable_Method")
        Limiting_Variable_Method.resize(628, 519)
        self.label = QtWidgets.QLabel(Limiting_Variable_Method)
        self.label.setGeometry(QtCore.QRect(20, 10, 491, 20))
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Limiting_Variable_Method)
        self.frame.setGeometry(QtCore.QRect(10, 30, 511, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 290, 491, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lv_save_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lv_save_lineedit.setObjectName("lv_save_lineedit")
        self.horizontalLayout_6.addWidget(self.lv_save_lineedit)
        self.lv_save_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.lv_save_browse.setObjectName("lv_save_browse")
        self.horizontalLayout_6.addWidget(self.lv_save_browse)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 210, 491, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lv_suffix_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lv_suffix_lineedit.setObjectName("lv_suffix_lineedit")
        self.horizontalLayout_9.addWidget(self.lv_suffix_lineedit)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 250, 491, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lv_intp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lv_intp.setObjectName("lv_intp")
        self.horizontalLayout_10.addWidget(self.lv_intp)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 491, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lv_sourceid_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lv_sourceid_lineedit.setObjectName("lv_sourceid_lineedit")
        self.horizontalLayout_5.addWidget(self.lv_sourceid_lineedit)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 491, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lv_dict_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lv_dict_lineedit.setText("")
        self.lv_dict_lineedit.setObjectName("lv_dict_lineedit")
        self.horizontalLayout_3.addWidget(self.lv_dict_lineedit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lv_class_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lv_class_lineedit.setObjectName("lv_class_lineedit")
        self.horizontalLayout_2.addWidget(self.lv_class_lineedit)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 50, 491, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lv_anc_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.lv_anc_lineedit.setObjectName("lv_anc_lineedit")
        self.horizontalLayout_4.addWidget(self.lv_anc_lineedit)
        self.lv_anc_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.lv_anc_browse.setObjectName("lv_anc_browse")
        self.horizontalLayout_4.addWidget(self.lv_anc_browse)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMouseTracking(False)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lv_source_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lv_source_lineedit.setObjectName("lv_source_lineedit")
        self.horizontalLayout.addWidget(self.lv_source_lineedit)
        self.lv_source_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.lv_source_browse.setObjectName("lv_source_browse")
        self.horizontalLayout.addWidget(self.lv_source_browse)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Limiting_Variable_Method)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 370, 511, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lv_progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.lv_progressBar.setProperty("value", 0)
        self.lv_progressBar.setObjectName("lv_progressBar")
        self.horizontalLayout_7.addWidget(self.lv_progressBar)
        self.lv_run_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.lv_run_prog.setObjectName("lv_run_prog")
        self.horizontalLayout_7.addWidget(self.lv_run_prog)
        self.lv_cancel_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.lv_cancel_prog.setObjectName("lv_cancel_prog")
        self.horizontalLayout_7.addWidget(self.lv_cancel_prog)
        self.frame.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget_6.raise_()

        self.retranslateUi(Limiting_Variable_Method)
        QtCore.QMetaObject.connectSlotsByName(Limiting_Variable_Method)
        Limiting_Variable_Method.setTabOrder(self.lv_source_lineedit, self.lv_source_browse)
        Limiting_Variable_Method.setTabOrder(self.lv_source_browse, self.lv_anc_lineedit)
        Limiting_Variable_Method.setTabOrder(self.lv_anc_lineedit, self.lv_anc_browse)
        Limiting_Variable_Method.setTabOrder(self.lv_anc_browse, self.lv_class_lineedit)
        Limiting_Variable_Method.setTabOrder(self.lv_class_lineedit, self.lv_dict_lineedit)
        Limiting_Variable_Method.setTabOrder(self.lv_dict_lineedit, self.lv_sourceid_lineedit)
        Limiting_Variable_Method.setTabOrder(self.lv_sourceid_lineedit, self.lv_suffix_lineedit)
        Limiting_Variable_Method.setTabOrder(self.lv_suffix_lineedit, self.lv_intp)
        Limiting_Variable_Method.setTabOrder(self.lv_intp, self.lv_save_lineedit)
        Limiting_Variable_Method.setTabOrder(self.lv_save_lineedit, self.lv_save_browse)
        Limiting_Variable_Method.setTabOrder(self.lv_save_browse, self.lv_run_prog)
        Limiting_Variable_Method.setTabOrder(self.lv_run_prog, self.lv_cancel_prog)

    def retranslateUi(self, Limiting_Variable_Method):
        _translate = QtCore.QCoreApplication.translate
        Limiting_Variable_Method.setWindowTitle(_translate("Limiting_Variable_Method", "Form"))
        self.label.setText(_translate("Limiting_Variable_Method", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Limiting Variable Method</span></p></body></html>"))
        self.label_7.setText(_translate("Limiting_Variable_Method", "Save as:"))
        self.lv_save_lineedit.setPlaceholderText(_translate("Limiting_Variable_Method", "filepath and name of output shapefile"))
        self.lv_save_browse.setText(_translate("Limiting_Variable_Method", "Browse"))
        self.label_9.setText(_translate("Limiting_Variable_Method", "New Field Suffix:"))
        self.lv_suffix_lineedit.setPlaceholderText(_translate("Limiting_Variable_Method", "Suffix for new interpolated fields ex: _intp "))
        self.label_10.setText(_translate("Limiting_Variable_Method", "Interpolation Field(s):"))
        self.lv_intp.setPlaceholderText(_translate("Limiting_Variable_Method", "Name(s) of the field(s) to interpolate, separated by spaces"))
        self.label_6.setText(_translate("Limiting_Variable_Method", "Source Identifier (optional):"))
        self.lv_sourceid_lineedit.setPlaceholderText(_translate("Limiting_Variable_Method", "Field that identifies source polygons (optional) ex: Tract_ID"))
        self.label_4.setText(_translate("Limiting_Variable_Method", "Class Dictionary:"))
        self.lv_dict_lineedit.setPlaceholderText(_translate("Limiting_Variable_Method", "ex: Urban:5000, Suburban:2000, Rural:500"))
        self.label_3.setText(_translate("Limiting_Variable_Method", "Class Field:"))
        self.lv_class_lineedit.setPlaceholderText(_translate("Limiting_Variable_Method", "Field containing area-class categories"))
        self.label_5.setText(_translate("Limiting_Variable_Method", "Ancillary Shapefile:"))
        self.lv_anc_lineedit.setPlaceholderText(_translate("Limiting_Variable_Method", "filepath of ancillary shapefile"))
        self.lv_anc_browse.setText(_translate("Limiting_Variable_Method", "Browse"))
        self.label_2.setText(_translate("Limiting_Variable_Method", "Source Shapefile:"))
        self.lv_source_lineedit.setPlaceholderText(_translate("Limiting_Variable_Method", "filepath and name of the source shapefile"))
        self.lv_source_browse.setText(_translate("Limiting_Variable_Method", "Browse"))
        self.lv_run_prog.setText(_translate("Limiting_Variable_Method", "Run"))
        self.lv_cancel_prog.setText(_translate("Limiting_Variable_Method", "Cancel"))

