# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nclass_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_N_Class_Method(object):
    def setupUi(self, N_Class_Method):
        N_Class_Method.setObjectName("N_Class_Method")
        N_Class_Method.resize(566, 489)
        self.label = QtWidgets.QLabel(N_Class_Method)
        self.label.setGeometry(QtCore.QRect(20, 10, 491, 20))
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(N_Class_Method)
        self.frame.setGeometry(QtCore.QRect(10, 30, 511, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 290, 491, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.n_save_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.n_save_lineedit.setObjectName("n_save_lineedit")
        self.horizontalLayout_6.addWidget(self.n_save_lineedit)
        self.n_save_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.n_save_browse.setObjectName("n_save_browse")
        self.horizontalLayout_6.addWidget(self.n_save_browse)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 210, 491, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.n_suffix_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.n_suffix_lineedit.setObjectName("n_suffix_lineedit")
        self.horizontalLayout_9.addWidget(self.n_suffix_lineedit)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 250, 491, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.n_intp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.n_intp.setObjectName("n_intp")
        self.horizontalLayout_10.addWidget(self.n_intp)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 491, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.n_sourceid_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.n_sourceid_lineedit.setObjectName("n_sourceid_lineedit")
        self.horizontalLayout_5.addWidget(self.n_sourceid_lineedit)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 491, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.n_dict_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.n_dict_lineedit.setText("")
        self.n_dict_lineedit.setObjectName("n_dict_lineedit")
        self.horizontalLayout_3.addWidget(self.n_dict_lineedit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.n_field_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.n_field_lineedit.setObjectName("n_field_lineedit")
        self.horizontalLayout_2.addWidget(self.n_field_lineedit)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 50, 491, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.n_anc_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.n_anc_lineedit.setObjectName("n_anc_lineedit")
        self.horizontalLayout_4.addWidget(self.n_anc_lineedit)
        self.n_anc_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.n_anc_browse.setObjectName("n_anc_browse")
        self.horizontalLayout_4.addWidget(self.n_anc_browse)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMouseTracking(False)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.n_source_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.n_source_lineedit.setObjectName("n_source_lineedit")
        self.horizontalLayout.addWidget(self.n_source_lineedit)
        self.n_source_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.n_source_browse.setObjectName("n_source_browse")
        self.horizontalLayout.addWidget(self.n_source_browse)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(N_Class_Method)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 370, 511, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.n_progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.n_progressBar.setProperty("value", 0)
        self.n_progressBar.setObjectName("n_progressBar")
        self.horizontalLayout_7.addWidget(self.n_progressBar)
        self.n_run_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.n_run_prog.setObjectName("n_run_prog")
        self.horizontalLayout_7.addWidget(self.n_run_prog)
        self.n_cancel_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.n_cancel_prog.setObjectName("n_cancel_prog")
        self.horizontalLayout_7.addWidget(self.n_cancel_prog)
        self.frame.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget_6.raise_()

        self.retranslateUi(N_Class_Method)
        QtCore.QMetaObject.connectSlotsByName(N_Class_Method)
        N_Class_Method.setTabOrder(self.n_source_lineedit, self.n_source_browse)
        N_Class_Method.setTabOrder(self.n_source_browse, self.n_anc_lineedit)
        N_Class_Method.setTabOrder(self.n_anc_lineedit, self.n_anc_browse)
        N_Class_Method.setTabOrder(self.n_anc_browse, self.n_field_lineedit)
        N_Class_Method.setTabOrder(self.n_field_lineedit, self.n_dict_lineedit)
        N_Class_Method.setTabOrder(self.n_dict_lineedit, self.n_sourceid_lineedit)
        N_Class_Method.setTabOrder(self.n_sourceid_lineedit, self.n_suffix_lineedit)
        N_Class_Method.setTabOrder(self.n_suffix_lineedit, self.n_intp)
        N_Class_Method.setTabOrder(self.n_intp, self.n_save_lineedit)
        N_Class_Method.setTabOrder(self.n_save_lineedit, self.n_save_browse)
        N_Class_Method.setTabOrder(self.n_save_browse, self.n_run_prog)
        N_Class_Method.setTabOrder(self.n_run_prog, self.n_cancel_prog)

    def retranslateUi(self, N_Class_Method):
        _translate = QtCore.QCoreApplication.translate
        N_Class_Method.setWindowTitle(_translate("N_Class_Method", "Form"))
        self.label.setText(_translate("N_Class_Method", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">N-Class Method</span></p></body></html>"))
        self.label_7.setText(_translate("N_Class_Method", "Save as:"))
        self.n_save_lineedit.setPlaceholderText(_translate("N_Class_Method", "filepath and name of output shapefile"))
        self.n_save_browse.setText(_translate("N_Class_Method", "Browse"))
        self.label_9.setText(_translate("N_Class_Method", "New Field Suffix:"))
        self.n_suffix_lineedit.setPlaceholderText(_translate("N_Class_Method", "Suffix for new interpolated fields ex: _intp "))
        self.label_10.setText(_translate("N_Class_Method", "Interpolation Field(s):"))
        self.n_intp.setPlaceholderText(_translate("N_Class_Method", "Name(s) of the field(s) to interpolate, space separated"))
        self.label_6.setText(_translate("N_Class_Method", "Source Identifier (optional):"))
        self.n_sourceid_lineedit.setPlaceholderText(_translate("N_Class_Method", "Field that identifies source polygons (optional) ex: Tract_ID"))
        self.label_4.setText(_translate("N_Class_Method", "Class Dictionary:"))
        self.n_dict_lineedit.setPlaceholderText(_translate("N_Class_Method", "ex: Urban: 0.75, Suburban:0.20, Rural:0.05"))
        self.label_3.setText(_translate("N_Class_Method", "Class Field:"))
        self.n_field_lineedit.setPlaceholderText(_translate("N_Class_Method", "Field containing area-class categories"))
        self.label_5.setText(_translate("N_Class_Method", "Ancillary Shapefile:"))
        self.n_anc_lineedit.setPlaceholderText(_translate("N_Class_Method", "filepath and name of the ancillary shapefile"))
        self.n_anc_browse.setText(_translate("N_Class_Method", "Browse"))
        self.label_2.setText(_translate("N_Class_Method", "Source Shapefile:"))
        self.n_source_lineedit.setPlaceholderText(_translate("N_Class_Method", "filepath and name of the source shapefile"))
        self.n_source_browse.setText(_translate("N_Class_Method", "Browse"))
        self.n_run_prog.setText(_translate("N_Class_Method", "Run"))
        self.n_cancel_prog.setText(_translate("N_Class_Method", "Cancel"))

