# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parcel_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Parcel_Method(object):
    def setupUi(self, Parcel_Method):
        Parcel_Method.setObjectName("Parcel_Method")
        Parcel_Method.resize(628, 519)
        self.label = QtWidgets.QLabel(Parcel_Method)
        self.label.setGeometry(QtCore.QRect(20, 10, 491, 20))
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Parcel_Method)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 491, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMouseTracking(False)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.parcel_source_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.parcel_source_lineedit.setObjectName("parcel_source_lineedit")
        self.horizontalLayout.addWidget(self.parcel_source_lineedit)
        self.parcel_source_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.parcel_source_browse.setObjectName("parcel_source_browse")
        self.horizontalLayout.addWidget(self.parcel_source_browse)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Parcel_Method)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 80, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.parcel_anc_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.parcel_anc_lineedit.setObjectName("parcel_anc_lineedit")
        self.horizontalLayout_2.addWidget(self.parcel_anc_lineedit)
        self.parcel_anc_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.parcel_anc_browse.setObjectName("parcel_anc_browse")
        self.horizontalLayout_2.addWidget(self.parcel_anc_browse)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Parcel_Method)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 120, 491, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.parcel_tu = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.parcel_tu.setText("")
        self.parcel_tu.setObjectName("parcel_tu")
        self.horizontalLayout_3.addWidget(self.parcel_tu)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Parcel_Method)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 160, 491, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.parcel_ru = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.parcel_ru.setObjectName("parcel_ru")
        self.horizontalLayout_5.addWidget(self.parcel_ru)
        self.frame = QtWidgets.QFrame(Parcel_Method)
        self.frame.setGeometry(QtCore.QRect(10, 30, 511, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 290, 491, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.parcel_save_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.parcel_save_lineedit.setObjectName("parcel_save_lineedit")
        self.horizontalLayout_6.addWidget(self.parcel_save_lineedit)
        self.parcel_save_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.parcel_save_browse.setObjectName("parcel_save_browse")
        self.horizontalLayout_6.addWidget(self.parcel_save_browse)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 210, 491, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.parcel_ra = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.parcel_ra.setObjectName("parcel_ra")
        self.horizontalLayout_8.addWidget(self.parcel_ra)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 170, 491, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.parcel_ba = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.parcel_ba.setObjectName("parcel_ba")
        self.horizontalLayout_9.addWidget(self.parcel_ba)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 250, 491, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.parcel_intp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.parcel_intp.setObjectName("parcel_intp")
        self.horizontalLayout_10.addWidget(self.parcel_intp)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Parcel_Method)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 370, 511, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.parcel_progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.parcel_progressBar.setProperty("value", 0)
        self.parcel_progressBar.setObjectName("parcel_progressBar")
        self.horizontalLayout_7.addWidget(self.parcel_progressBar)
        self.parcel_run_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.parcel_run_prog.setObjectName("parcel_run_prog")
        self.horizontalLayout_7.addWidget(self.parcel_run_prog)
        self.parcel_cancel_prog = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.parcel_cancel_prog.setObjectName("parcel_cancel_prog")
        self.horizontalLayout_7.addWidget(self.parcel_cancel_prog)
        self.frame.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_6.raise_()

        self.retranslateUi(Parcel_Method)
        QtCore.QMetaObject.connectSlotsByName(Parcel_Method)
        Parcel_Method.setTabOrder(self.parcel_source_lineedit, self.parcel_source_browse)
        Parcel_Method.setTabOrder(self.parcel_source_browse, self.parcel_anc_lineedit)
        Parcel_Method.setTabOrder(self.parcel_anc_lineedit, self.parcel_anc_browse)
        Parcel_Method.setTabOrder(self.parcel_anc_browse, self.parcel_tu)
        Parcel_Method.setTabOrder(self.parcel_tu, self.parcel_ru)
        Parcel_Method.setTabOrder(self.parcel_ru, self.parcel_ba)
        Parcel_Method.setTabOrder(self.parcel_ba, self.parcel_ra)
        Parcel_Method.setTabOrder(self.parcel_ra, self.parcel_intp)
        Parcel_Method.setTabOrder(self.parcel_intp, self.parcel_save_lineedit)
        Parcel_Method.setTabOrder(self.parcel_save_lineedit, self.parcel_save_browse)
        Parcel_Method.setTabOrder(self.parcel_save_browse, self.parcel_run_prog)
        Parcel_Method.setTabOrder(self.parcel_run_prog, self.parcel_cancel_prog)

    def retranslateUi(self, Parcel_Method):
        _translate = QtCore.QCoreApplication.translate
        Parcel_Method.setWindowTitle(_translate("Parcel_Method", "Form"))
        self.label.setText(_translate("Parcel_Method", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parcel Method</span></p></body></html>"))
        self.label_2.setText(_translate("Parcel_Method", "Source Shapefile:"))
        self.parcel_source_lineedit.setPlaceholderText(_translate("Parcel_Method", "filepath and name of the source shapefile"))
        self.parcel_source_browse.setText(_translate("Parcel_Method", "Browse"))
        self.label_3.setText(_translate("Parcel_Method", "Parcel Shapefile:"))
        self.parcel_anc_lineedit.setPlaceholderText(_translate("Parcel_Method", "filepath and name of the parcel shapefile"))
        self.parcel_anc_browse.setText(_translate("Parcel_Method", "Browse"))
        self.label_4.setText(_translate("Parcel_Method", "Total Units Field:"))
        self.parcel_tu.setPlaceholderText(_translate("Parcel_Method", "Name of the field containing the total number of units per parcel"))
        self.label_6.setText(_translate("Parcel_Method", "Residential Units Field"))
        self.parcel_ru.setPlaceholderText(_translate("Parcel_Method", "Name of the field containing the number of residential units per parcel"))
        self.label_7.setText(_translate("Parcel_Method", "Save as:"))
        self.parcel_save_lineedit.setPlaceholderText(_translate("Parcel_Method", "filepath and name of output shapefile"))
        self.parcel_save_browse.setText(_translate("Parcel_Method", "Browse"))
        self.label_8.setText(_translate("Parcel_Method", "Residential Area Field"))
        self.parcel_ra.setPlaceholderText(_translate("Parcel_Method", "Name of the field containing the residential area per parcel"))
        self.label_9.setText(_translate("Parcel_Method", "Building Area Field"))
        self.parcel_ba.setPlaceholderText(_translate("Parcel_Method", "Name of the field containing the building area per parcel"))
        self.label_10.setText(_translate("Parcel_Method", "Interpolation Fields"))
        self.parcel_intp.setPlaceholderText(_translate("Parcel_Method", "Name(s) of the field(s) to interpolate, space separated"))
        self.parcel_run_prog.setText(_translate("Parcel_Method", "Run"))
        self.parcel_cancel_prog.setText(_translate("Parcel_Method", "Cancel"))

